#makefile para Mario Bross


compile_plataforma: gcc /Plataforma/*.c /Comunes/*.c /Comunes/Serializadores/*.c /Comunes/comunes/*.c /Comunes/comunes/collections/*.c -lncurses -lpthread -I/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -L/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -o Plataforma
run_plataforma: ./Plataforma

compile_personaje: sudo gcc /home/utnso/tp-20131c-not-an-issue-but-a-feature/Personaje/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/Serializadores/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/comunes/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/comunes/collections/*.c -lncurses -lpthread -I/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -L/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -o Personaje
run_personaje: ./Personaje

compile_nivel: sudo gcc /home/utnso/tp-20131c-not-an-issue-but-a-feature/Nivel/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/Serializadores/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/comunes/*.c /home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/comunes/collections/*.c -lncurses -lpthread -I/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -L/home/utnso/tp-20131c-not-an-issue-but-a-feature/Comunes/ -o Nivel
run_nivel: ./Nivel
